/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_card2digit_CameraPreview */

#ifndef _Included_com_example_card2digit_CameraPreview
#define _Included_com_example_card2digit_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_card2digit_CameraPreview
 * Method:    ocr
 * Signature: ([BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_card2digit_CameraPreview_ocr
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
